export const ALBUMS = [
  {
    Id: 1,
    genre: 1,
    name: 'The Dark Side of the Moon',
    artist: 'Pink Floyd',
    // releaseDate: new date('1973, 2, 1'),
    coverArt: require('../../assets/coverArts/Thedarksideofthemoon.jpg'),
  },
  {
    Id: 2,
    genre: 1,
    name: 'Weezer (Blue Album)',
    artist: 'Weezer',
    // releaseDate: new date('1994, 5, 1'),
    coverArt: require('../../assets/coverArts/Weezer.jpg'),
  },
  {
    Id: 3,
    genre: 1,
    name: 'Spiderland',
    artist: 'Slint',
    // releaseDate: new date('1991, 3, 27'),
    coverArt: require('../../assets/coverArts/Spiderland.jpg'),
  },
  {
    Id: 4,
    genre: 2,
    name: 'MM... FOOD',
    artist: 'MF DOOM',
    // releaseDate: new date('1991, 3, 27'),
    coverArt: require('../../assets/coverArts/Mmfood.jpg'),
  },
  {
    Id: 5,
    genre: 2,
    name: 'My Beautiful Dark Twisted Fantasy',
    artist: 'Kanye West',
    // releaseDate: new date('1991, 3, 27'),
    coverArt: require('../../assets/coverArts/Mybeautifuldarktwistedfantasy.jpg'),
  },
  {
    Id: 6,
    genre: 2,
    name: 'Illmatic',
    artist: 'Nas',
    // releaseDate: new date('1991, 3, 27'),
    coverArt: require('../../assets/coverArts/Ilmatic.jpg'),
  },
  {
    Id: 7,
    genre: 3,
    name: 'Ride The Lightning',
    artist: 'Metallica',
    // releaseDate: new date('1991, 3, 27'),
    coverArt: require('../../assets/coverArts/Ridethelightning.jpg'),
  },
  {
    Id: 8,
    genre: 3,
    name: 'Around The Fur',
    artist: 'Deftones',
    // releaseDate: new date('1991, 3, 27'),
    coverArt: require('../../assets/coverArts/Aroundthefur.jpg'),
  },
  {
    Id: 9,
    genre: 3,
    name: 'Symbolic',
    artist: 'Death',
    // releaseDate: new date('1991, 3, 27'),
    coverArt: require('../../assets/coverArts/Symbolic.jpg'),
  },
];
